# LeRobot Policy Controller - Example Parameters
#
# This file contains example parameters for the policy controller node.
# Copy and modify as needed for your specific setup.
#
# Usage:
#   ros2 run ledog_policy_controller policy_controller_node \
#       --ros-args --params-file config/policy_controller_params.yaml

policy_controller_node:
  ros__parameters:
    # Conda environment configuration
    conda_env_name: "lerobot"
    conda_base_path: "~/miniconda3"  # Change to ~/anaconda3 if using anaconda
    
    # Process management
    shutdown_timeout: 5.0  # Seconds to wait before force kill
    
    # Robot configuration (currently not used in command, but available)
    robot_id: "follower_1"
    robot_port: "/dev/ttyACM0"
    robot_type: "so100_follower"
    
    # Camera configuration
    camera_top_index: 2    # Device index for top camera
    camera_left_index: 0   # Device index for left camera
    
    # Dataset configuration
    dataset_base_repo_id: "zhoumiaosen/eval_policy_act"  # Timestamp will be appended automatically

